cmake_minimum_required(VERSION 3.22)
project(sunshine_transport LANGUAGES C CXX)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_STANDARD 17)
set(ENET_NO_INSTALL ON CACHE BOOL "" FORCE)
add_subdirectory(enet)
set(OPUS_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(OPUS_BUILD_PROGRAMS OFF CACHE BOOL "" FORCE)
set(OPUS_INSTALL_PKG_CONFIG_MODULE OFF CACHE BOOL "" FORCE)
set(OPUS_INSTALL_CMAKE_CONFIG_MODULE OFF CACHE BOOL "" FORCE)
add_subdirectory(opus)
add_library(nanors STATIC nanors/rs.c nanors/deps/obl/oblas_common.c nanors/deps/obl/oblas_lite.c)
target_include_directories(nanors PUBLIC nanors nanors/deps/obl)
add_library(sunshine_transport SHARED transport.cpp)
if(NOT ANDROID)
    find_package(JNI REQUIRED)
    target_include_directories(sunshine_transport PRIVATE ${JNI_INCLUDE_DIRS})
endif()
target_include_directories(sunshine_transport PRIVATE enet/include opus/include)
target_link_libraries(sunshine_transport PRIVATE enet opus nanors)
